//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public long IdAsistencia { get; set; }
        public Nullable<System.DateTime> FechaAsistencia { get; set; }
        public Nullable<System.DateTime> FechaRenovacion { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<long> IdSolicitud { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
