//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraCliente
    {
        public long IdBitacoraCliente { get; set; }
        public string NombreOperacion { get; set; }
        public Nullable<System.DateTime> FechaOperacion { get; set; }
        public Nullable<long> IdCliente { get; set; }
        public Nullable<long> IdBitacoraLogin { get; set; }
    
        public virtual BitacoraLogin BitacoraLogin { get; set; }
    }
}
