//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraLogin
    {
        public long IdBitLogin { get; set; }
        public string NombreEmpleado { get; set; }
        public string NombreUsuario { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.TimeSpan> HoraIngreso { get; set; }
        public Nullable<System.TimeSpan> HoraSalida { get; set; }
    }
}
