//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public long IdCategoria { get; set; }
        public string NombreCategoria { get; set; }
        public int EstadoCategoria { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
