//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credito
    {
        public Credito()
        {
            this.Cuota = new HashSet<Cuota>();
        }
    
        public long IdCredito { get; set; }
        public System.DateTime FechaCredito { get; set; }
        public System.DateTime FechaPlazo { get; set; }
        public double Monto { get; set; }
        public Nullable<long> IdSolicitud { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
        public virtual ICollection<Cuota> Cuota { get; set; }
    }
}
