//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuento
    {
        public Descuento()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public long IdDescuento { get; set; }
        public string NombreDescuento { get; set; }
        public double Monto { get; set; }
        public Nullable<int> EstadoDescuento { get; set; }
    
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
