//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSolicitudCompra
    {
        public long IdSolicitudCompra { get; set; }
        public long IdPrecio { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Precio Precio { get; set; }
        public virtual SolicitudCompra SolicitudCompra { get; set; }
    }
}
