//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Horario = new HashSet<Horario>();
        }
    
        public long IdPersona { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public int EstadoEmpleado { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
