//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public long IdFactura { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<long> Nit { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public long CodigoAutorizacion { get; set; }
        public string CodigoControl { get; set; }
        public System.DateTime FechaLimiteEmision { get; set; }
        public byte[] CodigoQR { get; set; }
        public double Monto { get; set; }
        public Nullable<long> IdSolicitud { get; set; }
        public Nullable<long> IdPago { get; set; }
    
        public virtual Pago Pago { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
