//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbGimnasioSportLineEntities : DbContext
    {
        public dbGimnasioSportLineEntities()
            : base("name=dbGimnasioSportLineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Año> Año { get; set; }
        public DbSet<Asistencia> Asistencia { get; set; }
        public DbSet<BitacoraLogin> BitacoraLogin { get; set; }
        public DbSet<BitacoraSolicitudVenta> BitacoraSolicitudVenta { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Ciudad> Ciudad { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Credito> Credito { get; set; }
        public DbSet<Cuota> Cuota { get; set; }
        public DbSet<Descuento> Descuento { get; set; }
        public DbSet<DetalleSolicitud> DetalleSolicitud { get; set; }
        public DbSet<DetalleSolicitudCompra> DetalleSolicitudCompra { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<Horario> Horario { get; set; }
        public DbSet<Mes> Mes { get; set; }
        public DbSet<Pago> Pago { get; set; }
        public DbSet<Permiso> Permiso { get; set; }
        public DbSet<Persona> Persona { get; set; }
        public DbSet<Plazo> Plazo { get; set; }
        public DbSet<Precio> Precio { get; set; }
        public DbSet<Producto> Producto { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RolPermiso> RolPermiso { get; set; }
        public DbSet<Servicio> Servicio { get; set; }
        public DbSet<Solicitud> Solicitud { get; set; }
        public DbSet<SolicitudCompra> SolicitudCompra { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<TipoSolicitud> TipoSolicitud { get; set; }
        public DbSet<Turno> Turno { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Zona> Zona { get; set; }
        public DbSet<VCategoria> VCategoria { get; set; }
        public DbSet<VClienteAsistencia> VClienteAsistencia { get; set; }
        public DbSet<VClienteCreditoGeneral> VClienteCreditoGeneral { get; set; }
        public DbSet<VClienteDetalleCredito> VClienteDetalleCredito { get; set; }
        public DbSet<VClienteGeneral> VClienteGeneral { get; set; }
        public DbSet<VClientePagoServicio> VClientePagoServicio { get; set; }
        public DbSet<VClientes> VClientes { get; set; }
        public DbSet<VClienteServicio> VClienteServicio { get; set; }
        public DbSet<VClienteSolicitudDetalleGeneral> VClienteSolicitudDetalleGeneral { get; set; }
        public DbSet<VClienteSolicitudDiario> VClienteSolicitudDiario { get; set; }
        public DbSet<VClienteSolicitudGeneral> VClienteSolicitudGeneral { get; set; }
        public DbSet<VClienteSolicitudGeneralConsolidado> VClienteSolicitudGeneralConsolidado { get; set; }
        public DbSet<VClienteSolicitudServicioPlanes> VClienteSolicitudServicioPlanes { get; set; }
        public DbSet<VCumpleañeros> VCumpleañeros { get; set; }
        public DbSet<VCumpleañerosFoto> VCumpleañerosFoto { get; set; }
        public DbSet<VCumpleañerosGral> VCumpleañerosGral { get; set; }
        public DbSet<VDescuento> VDescuento { get; set; }
        public DbSet<VDetalleSolicitudProducto> VDetalleSolicitudProducto { get; set; }
        public DbSet<VDetalleSolicitudProductoServicio> VDetalleSolicitudProductoServicio { get; set; }
        public DbSet<VDetalleSolicitudServicio> VDetalleSolicitudServicio { get; set; }
        public DbSet<VDetalleSolicitudServicioPago> VDetalleSolicitudServicioPago { get; set; }
        public DbSet<VEmpleados> VEmpleados { get; set; }
        public DbSet<VEmpleadosActivoSinUser> VEmpleadosActivoSinUser { get; set; }
        public DbSet<VFacturaGeneral> VFacturaGeneral { get; set; }
        public DbSet<VHorarioServicioEstadoPlan> VHorarioServicioEstadoPlan { get; set; }
        public DbSet<VIngresoGeneral> VIngresoGeneral { get; set; }
        public DbSet<VIngresoGeneralConsolidado> VIngresoGeneralConsolidado { get; set; }
        public DbSet<VPermiso> VPermiso { get; set; }
        public DbSet<VProducto> VProducto { get; set; }
        public DbSet<VProductoInventarioDiario> VProductoInventarioDiario { get; set; }
        public DbSet<VRol> VRol { get; set; }
        public DbSet<VRolPermiso> VRolPermiso { get; set; }
        public DbSet<VServicioActivo> VServicioActivo { get; set; }
        public DbSet<VSolicitudGeneral> VSolicitudGeneral { get; set; }
        public DbSet<VSolicitudGeneralAño> VSolicitudGeneralAño { get; set; }
        public DbSet<VSolicitudGeneralConsolidado> VSolicitudGeneralConsolidado { get; set; }
        public DbSet<VSolicitudGeneralMes> VSolicitudGeneralMes { get; set; }
        public DbSet<VSolicitudProducto> VSolicitudProducto { get; set; }
        public DbSet<VSolicitudProductoGeneral> VSolicitudProductoGeneral { get; set; }
        public DbSet<VSolicitudServicio> VSolicitudServicio { get; set; }
        public DbSet<VSolicitudServicioCredito> VSolicitudServicioCredito { get; set; }
        public DbSet<VSolicitudServicioPago> VSolicitudServicioPago { get; set; }
        public DbSet<VUsuario> VUsuario { get; set; }
        public DbSet<VUsuarioActivo> VUsuarioActivo { get; set; }
        public DbSet<VUsuarioRolPermisos> VUsuarioRolPermisos { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_VerificarPersonaExiste(Nullable<int> cedula)
        {
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_VerificarPersonaExiste", cedulaParameter);
        }
    }
}
