//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public Pago()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public long IdPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Monto { get; set; }
        public int EstadoPago { get; set; }
        public Nullable<long> IdSolicitud { get; set; }
        public Nullable<long> IdPrecio { get; set; }
    
        public virtual DetalleSolicitud DetalleSolicitud { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
