//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public Precio()
        {
            this.DetalleSolicitud = new HashSet<DetalleSolicitud>();
            this.DetalleSolicitudCompra = new HashSet<DetalleSolicitudCompra>();
        }
    
        public long IdPrecio { get; set; }
        public Nullable<double> PrecioCompra { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public Nullable<double> PrecioDiario { get; set; }
        public Nullable<double> PrecioQuincenal { get; set; }
        public Nullable<double> PrecioMensual { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<long> IdProducto { get; set; }
        public Nullable<long> IdServicio { get; set; }
        public Nullable<int> EstadoPrecio { get; set; }
    
        public virtual ICollection<DetalleSolicitud> DetalleSolicitud { get; set; }
        public virtual ICollection<DetalleSolicitudCompra> DetalleSolicitudCompra { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
