//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Precio = new HashSet<Precio>();
        }
    
        public long IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public int Stock { get; set; }
        public Nullable<long> IdCategoria { get; set; }
        public int EstadoProducto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Precio> Precio { get; set; }
    }
}
