//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.Horario = new HashSet<Horario>();
            this.Precio = new HashSet<Precio>();
        }
    
        public long IdServicio { get; set; }
        public string NombreServicio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public string RangoDia { get; set; }
        public int EstadoServicio { get; set; }
    
        public virtual ICollection<Horario> Horario { get; set; }
        public virtual ICollection<Precio> Precio { get; set; }
    }
}
