//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCompra
    {
        public SolicitudCompra()
        {
            this.DetalleSolicitudCompra = new HashSet<DetalleSolicitudCompra>();
        }
    
        public long IdSolicitudCompra { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    
        public virtual ICollection<DetalleSolicitudCompra> DetalleSolicitudCompra { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
