//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public Solicitud()
        {
            this.Asistencia = new HashSet<Asistencia>();
            this.Credito = new HashSet<Credito>();
            this.DetalleSolicitud = new HashSet<DetalleSolicitud>();
            this.Factura = new HashSet<Factura>();
            this.Horario = new HashSet<Horario>();
        }
    
        public long IdSolicitud { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaCulminacion { get; set; }
        public int EstadoSolicitud { get; set; }
        public Nullable<int> TipoPago { get; set; }
        public Nullable<long> IdCliente { get; set; }
        public Nullable<long> IdEmpleado { get; set; }
        public Nullable<long> IdTipoSolicitud { get; set; }
        public Nullable<long> IdPlazo { get; set; }
        public Nullable<long> IdDescuento { get; set; }
        public Nullable<long> IdUsuario { get; set; }
    
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual ICollection<Credito> Credito { get; set; }
        public virtual Descuento Descuento { get; set; }
        public virtual ICollection<DetalleSolicitud> DetalleSolicitud { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<Horario> Horario { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual Plazo Plazo { get; set; }
        public virtual TipoSolicitud TipoSolicitud { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
