//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Solicitud = new HashSet<Solicitud>();
            this.SolicitudCompra = new HashSet<SolicitudCompra>();
        }
    
        public long IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public long IdPersona { get; set; }
        public Nullable<int> EstadoUsuario { get; set; }
        public Nullable<long> IdRol { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        public virtual ICollection<SolicitudCompra> SolicitudCompra { get; set; }
    }
}
