//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClientePagoServicio
    {
        public long IdSolicitud { get; set; }
        public long IdPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string NombreServicio { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<double> MontoPago { get; set; }
    }
}
