//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClienteDetalleCredito
    {
        public long CodVenta { get; set; }
        public long CodCrédito { get; set; }
        public long CodCliente { get; set; }
        public string NombreCliente { get; set; }
        public long CédulaIdentidad { get; set; }
        public System.DateTime FechaCredito { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public int Cantidad { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
