//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClienteSolicitudDiario
    {
        public long IdSolicitud { get; set; }
        public long Código { get; set; }
        public string NombreCliente { get; set; }
        public long CédulaIdentidad { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string NombreServicio { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
