//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClienteSolicitudGeneralConsolidado
    {
        public long CodVenta { get; set; }
        public long CodCliente { get; set; }
        public string NombreCliente { get; set; }
        public long CédulaIdentidad { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<int> IdMes { get; set; }
        public string MesSolicitud { get; set; }
        public Nullable<int> AñoSolicitud { get; set; }
        public string Estado { get; set; }
        public string TipoSolicitud { get; set; }
        public string TipoPago { get; set; }
        public string Usuario { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> MontoDescuento { get; set; }
        public Nullable<double> MontoTotal { get; set; }
    }
}
