//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDetalleSolicitudProducto
    {
        public long IdSolicitud { get; set; }
        public long IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public long IdPrecio { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public int Cantidad { get; set; }
        public int Stock { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
