//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDetalleSolicitudServicioPago
    {
        public long IdSolicitud { get; set; }
        public long IdPago { get; set; }
        public long IdServicio { get; set; }
        public string NombreServicio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IdPlazo { get; set; }
        public long IdPrecio { get; set; }
        public Nullable<double> PrecioDiario { get; set; }
        public Nullable<double> PrecioQuincenal { get; set; }
        public Nullable<double> PrecioMensual { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> MontoDescuento { get; set; }
    }
}
