//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmpleados
    {
        public long Código { get; set; }
        public string NombreEmpleado { get; set; }
        public string NombrePersona { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public long CédulaIdentidad { get; set; }
        public string Teléfono { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public byte[] Foto { get; set; }
        public string Dirección { get; set; }
        public string Zona { get; set; }
        public string NombreCiudad { get; set; }
        public string NombreSucursal { get; set; }
    }
}
