//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFacturaGeneral
    {
        public long IdSolicitud { get; set; }
        public long IdFactura { get; set; }
        public long CodigoAutorizacion { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public string NombreCliente { get; set; }
        public long Carnet { get; set; }
        public string CodigoControl { get; set; }
        public Nullable<System.DateTime> FechaLimiteEmision { get; set; }
        public byte[] QR { get; set; }
        public string TipoPago { get; set; }
        public string NombreServicio { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> MontoDescuento { get; set; }
        public string Usuario { get; set; }
    }
}
