//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHorarioServicioEstadoPlan
    {
        public long IdHorario { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public string RangoDia { get; set; }
        public Nullable<long> IdServicio { get; set; }
        public Nullable<long> IdEmpleado { get; set; }
        public Nullable<long> IdCliente { get; set; }
        public Nullable<long> IdSolicitud { get; set; }
        public Nullable<long> IdTurno { get; set; }
        public string NombreTurno { get; set; }
        public string NombreServicio { get; set; }
        public string EstadoPlan { get; set; }
    }
}
