//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProductoInventarioDiario
    {
        public System.DateTime FechaSolicitud { get; set; }
        public string NombreCategoria { get; set; }
        public long IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<int> CantidadVendida { get; set; }
        public int Stock { get; set; }
    }
}
