//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSolicitudGeneral
    {
        public long IdSolicitud { get; set; }
        public Nullable<long> IdCliente { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Estado { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public string TipoPago { get; set; }
        public string TipoSolicitud { get; set; }
        public string Usuario { get; set; }
        public Nullable<long> IdDescuento { get; set; }
    }
}
