//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUsuario
    {
        public long Código { get; set; }
        public string NombreEmpleado { get; set; }
        public long IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public string NombreRol { get; set; }
        public string Estado { get; set; }
        public string NombreSucursal { get; set; }
        public string NombreCiudad { get; set; }
    }
}
