//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUsuarioRolPermisos
    {
        public string NombreSucursal { get; set; }
        public long IdPersona { get; set; }
        public string NombreEmpleado { get; set; }
        public byte[] Foto { get; set; }
        public long IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public long IdRol { get; set; }
        public string NombreRol { get; set; }
        public long IdPermiso { get; set; }
        public string NombrePermiso { get; set; }
        public int EstadoRolPermiso { get; set; }
    }
}
