//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zona
    {
        public Zona()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public long IdZona { get; set; }
        public string NombreZona { get; set; }
        public Nullable<long> IdCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
